# Generated by Django 4.0 on 2022-08-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_marker_date_of_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='date_of_update',
            field=models.DateTimeField(verbose_name='Дата обновления информации'),
        ),
    ]
