# Generated by Django 4.0 on 2022-08-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_marker_date_of_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='who',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='map.customuser', verbose_name='Кто'),
        ),
    ]
