# Generated by Django 4.0 on 2022-08-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_marker_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='who',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='map.customuser', verbose_name='Кто'),
        ),
    ]
